[theme]
base="dark"                                # Mode sombre
primaryColor="#F63366"                     # Couleur principale
backgroundColor="#0E1117"                  # Couleur de fond principale
secondaryBackgroundColor="#262730"         # Couleur de fond secondaire
textColor="#FAFAFA"                        # Couleur du texte
font="monospace"                           # Police (sans-serif, serif, monospace)

[server]
headless=false                              # Rend l'application exécutable sans interface
port=8501                                  # Port par défaut
enableCORS=false                           # Pour éviter des problèmes CORS (utile en déploiement)
enableXsrfProtection = false               # Désactive la protection XSRF